language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t devconnor/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true devconnor/react-test-app npm test

after_success:
  - docker build -t devconnor/docker-frontend ./frontend
  - docker build -t devconnor/docker-backend ./backend
  - docker build -t devconnor/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push devconnor/docker-frontend
  - docker push devconnor/docker-backend
  - docker push devconnor/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-full-stack"
  env: "Dockerfullstack-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-615258856034
  bucket_path: "docker-full-stack"
  on:
    branch: main
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY